id: IA54C7858
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T03:01:15+00:00'
last_modified: '2022-06-08T09:50:02.409993+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25749
  title: བདེན་པའི་སྨྲ་ལྕེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    EA7A:
      image_group_id: I1KG25751
      title: ''
      total_pages: 210
      order: 1
      base_file: EA7A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
