id: P009271
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25749
  title: བདེན་པའི་སྨྲ་ལྕེ།
  author: ''
  volumes:
    22aff9bb7790459ebc1d90a6cb0e4508:
      image_group_id: I1KG25751
      title: ''
      volume_number: 1
      total_pages: 210
