id: P009271
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:30:57.056620
source_metadata:
  id: bdr:W1KG25749
  title: བདེན་པའི་སྨྲ་ལྕེ།
  author: ''
  volumes:
    22aff9bb7790459ebc1d90a6cb0e4508:
      image_group_id: I1KG25751
      title: ''
      volume_number: 1
      total_pages: 210
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
